# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
    :hw16 => {
        :box_name => "centos/7",
    },
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.host_name = "hw16"
        box.vm.network "forwarded_port", guest: 8088, host: 8088
        box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            needsController = false
        end
        box.vm.provision "shell", inline: <<-SHELL
            yum install -y epel-release
            yum install -y setools-console policycoreutils-python policycoreutils-newrole selinux-policy-mls
            yum install -y nginx
            sed -ie 's/:80/:8088/g' /etc/nginx/nginx.conf
            sed -i 's/listen 80;/listen 8088;/'
            /etc/nginx/nginx.conf
            systemctl start nginx
            systemctl status nginx
        SHELL
    end
end
end
