Vagrant.configure("2") do |config|

  config.vm.define "deamon-server" do |server|
    config.vm.box = 'centos/7'

#    config.ssh.insert_key = 'false'
  
    server.vm.host_name = 'hw08-server'
    server.vm.network :private_network, ip: "192.168.56.11" 
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  
    end
  
  
  end