Vagrant.configure("2") do |config|

  config.vm.define "host-hw11" do |server|
    config.vm.box = 'centos/7'
    server.vm.host_name = 'host-hw11'
    server.vm.network :private_network, ip: "192.168.56.13" 
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    server.vm.provision :"file", source: "./ps-ax.sh", destination: "/home/vagrant/ps-ax.sh"
    end
  
  end
