# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network :private_network, ip: "192.168.56.11"
    server.vm.hostname = "hw06-server"
    server.vm.provision "shell", path: "server.sh"
  end

  config.vm.define "client" do |client|
    client.vm.network :private_network, ip: "192.168.56.22"
    client.vm.hostname = "hw06-client"
    client.vm.provision "shell", path: "client.sh"
  end

end
